cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED OPEN_LMM_TEST_MANIFEST OR
   NOT EXISTS "${OPEN_LMM_TEST_MANIFEST}")
  message(FATAL_ERROR "test manifest does not exist: ${OPEN_LMM_TEST_MANIFEST}")
endif()

file(STRINGS "${OPEN_LMM_TEST_MANIFEST}" manifest_lines)
list(LENGTH manifest_lines line_count)
if(line_count LESS 2)
  message(FATAL_ERROR "test manifest contains no registered tests")
endif()

list(GET manifest_lines 0 header)
if(NOT header STREQUAL
   "name\ttarget\tlayer\tmodule\towner\tinvariants\tlanes\tsanitizers")
  message(FATAL_ERROR "unexpected test manifest header: ${header}")
endif()
list(REMOVE_AT manifest_lines 0)

set(seen_names)
set(seen_targets)
foreach(line IN LISTS manifest_lines)
  string(REPLACE "\t" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(field_count LESS 7 OR field_count GREATER 8)
    message(FATAL_ERROR "invalid test manifest row: ${line}")
  endif()
  list(GET fields 0 name)
  list(GET fields 1 target)
  list(GET fields 2 layer)
  list(GET fields 3 module)
  list(GET fields 4 owner)
  list(GET fields 6 lanes)
  if(name IN_LIST seen_names)
    message(FATAL_ERROR "duplicate test name in manifest: ${name}")
  endif()
  if(target IN_LIST seen_targets)
    message(FATAL_ERROR "test target is registered more than once: ${target}")
  endif()
  if(NOT layer MATCHES "^L[1-6]$")
    message(FATAL_ERROR "invalid layer for ${name}: ${layer}")
  endif()
  if(module STREQUAL "" OR owner STREQUAL "" OR lanes STREQUAL "")
    message(FATAL_ERROR "missing ownership metadata for ${name}")
  endif()
  list(APPEND seen_names "${name}")
  list(APPEND seen_targets "${target}")
endforeach()

math(EXPR registered_count "${line_count} - 1")
message(STATUS "validated ${registered_count} registered tests")

if(NOT DEFINED OPEN_LMM_SOURCE_DIR)
  message(FATAL_ERROR "OPEN_LMM_SOURCE_DIR is required")
endif()
file(GLOB_RECURSE cmake_registration_sources
  "${OPEN_LMM_SOURCE_DIR}/*.cmake"
  "${OPEN_LMM_SOURCE_DIR}/CMakeLists.txt")
foreach(cmake_source IN LISTS cmake_registration_sources)
  if(cmake_source MATCHES "/test/cmake/OpenLmmTest.cmake$")
    continue()
  endif()
  file(READ "${cmake_source}" cmake_contents)
  if(cmake_contents MATCHES "(^|[\n\r])[ \t]*add_test[ \t]*\\(")
    message(FATAL_ERROR
      "raw add_test bypasses openlmm_add_test: ${cmake_source}")
  endif()
endforeach()

set(migration_manifest
  "${OPEN_LMM_SOURCE_DIR}/test/cmake/test_migration_manifest.tsv")
if(NOT EXISTS "${migration_manifest}")
  message(FATAL_ERROR "test migration manifest is missing")
endif()
file(STRINGS "${migration_manifest}" migration_lines)
list(LENGTH migration_lines migration_count)
if(migration_count LESS 2)
  message(FATAL_ERROR "test migration manifest has no dispositions")
endif()
list(GET migration_lines 0 migration_header)
if(NOT migration_header STREQUAL
   "previous_asset\tcurrent_asset\tdisposition\towner")
  message(FATAL_ERROR "unexpected migration manifest header")
endif()
list(REMOVE_AT migration_lines 0)
foreach(line IN LISTS migration_lines)
  string(REPLACE "\t" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 4)
    message(FATAL_ERROR "invalid migration disposition: ${line}")
  endif()
endforeach()
