# Private headers installed recursively before the canonical src/ layout was
# introduced. Keep the historical paths explicit so a fresh build can still
# clean an in-place package upgrade after the source files have moved.
set(_open_lmm_legacy_installed_headers_pre_src_layout
  common/pipeline.hpp
  common/pointcloud_utils.hpp
  common/pose_conversion.hpp
  common/profiling.hpp
  common/registration.hpp
  common/registration_log.hpp
  common/registration_pointcloud.hpp
  core/algorithm_config.hpp
  core/backend_optimizer/BetweenFactorWithAnchoring.h
  core/backend_optimizer/backend_optimizer_base.hpp
  core/backend_optimizer/backend_optimizer_incremental.hpp
  core/data_loader/data_loader_base.hpp
  core/data_loader/data_loader_file.hpp
  core/descriptor/built_in_descriptor_engine.hpp
  core/dynamic_remover/dynamic_remover_base.hpp
  core/dynamic_remover/dynamic_remover_offline.hpp
  core/dynamic_remover/dynamic_remover_online.hpp
  core/dynamic_remover/remover_factory/offline/interface_offline_plugin.hpp
  core/dynamic_remover/remover_factory/online/interface_online_plugin.hpp
  core/loop_detector/alignment_map_builder.hpp
  core/loop_detector/descriptor_alignment_proposer.hpp
  core/loop_detector/descriptor_factory/kdtree/database_kdtree.h
  core/loop_detector/descriptor_factory/kdtree/solid/solid.h
  core/loop_detector/kiss_alignment_proposer.hpp
  core/loop_detector/loop_detector_base.hpp
  core/loop_detector/loop_detector_kdtree.hpp
  core/loop_detector/map_alignment_coordinator.hpp
  core/loop_detector/map_alignment_refiner.hpp
  server/algorithm_provider.hpp
  server/artifact_repository.hpp
  server/bootstrap/algorithm_factory.hpp
  server/bootstrap/bootstrap_config.hpp
  server/bootstrap/runtime_bootstrapper.hpp
  server/execution/algorithm_context.hpp
  server/execution/alignment_artifact_store.hpp
  server/execution/alignment_executor.hpp
  server/execution/data_load_executor.hpp
  server/execution/execution_candidate.hpp
  server/execution/map_update_executor.hpp
  server/execution/optimize_executor.hpp
  server/execution/save_executor.hpp
  server/execution/stage_coordinator.hpp
  server/file_set_transaction.hpp
  server/nodes/data_load_node.hpp
  server/nodes/loop_detect_node.hpp
  server/nodes/map_update_node.hpp
  server/nodes/optimize_node.hpp
  server/output_repository.hpp
  server/pipeline_controller.hpp
  server/query/visualization_projector.hpp
  server/query/visualization_source.hpp
  server/resource_governor.hpp
  server/runtime_payload_builder.hpp
  server/runtime_service.hpp
  server/runtime_state.hpp
  server/runtime_state_store.hpp
  server/stage_executor.hpp
  server/stage_ports.hpp
  server/stage_runner.hpp
  server/transaction/runtime_reconfigurer.hpp
  utils/bounded_executor.hpp
  utils/config.hpp
  utils/config_impl.hpp
  utils/logging.hpp
)
