
if(OPEN_LMM_BUILD_DYNAMIC_REMOVER_HMM_MOS)
  add_subdirectory(hmm_mos)
endif()
if(OPEN_LMM_BUILD_DYNAMIC_REMOVER_DUFOMAP)
  add_subdirectory(dufomap)
endif()
if(OPEN_LMM_BUILD_DYNAMIC_REMOVER_OTD)
  add_subdirectory(otd)
endif()

add_library(remover_online INTERFACE)
foreach(remover_target IN ITEMS hmm_mos dufomap otd)
  if(TARGET ${remover_target})
    target_link_libraries(remover_online INTERFACE ${remover_target})
  endif()
endforeach()
